title: Sharda Learning Center
email: s.learnkarma@gmail.com
description: >-
  Learn to code by building real projects. Fast. Practical. No fluff.
baseurl: ""
url: "https://shardalearningcenter.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
permalink: /:year/:month/:day/:title/
