title: Sharda Learning Center
email: s.learnkarma@gmail.com
description: >-
  Learn to code by building real projects. Fast. Practical. No fluff.
baseurl: ""
url: "https://shardalearningcenter.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: "courses"
    values:
      layout: course
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
